using Survivor.Template;
using Survivor.Utils;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class BaseWeapon : MonoBehaviour
{
    public bool controlled = true;


    public int weaponId = -1;

    protected RankType rankType;

    protected WeaponTplInfo weaponInfo
    {
        get
        {
            return TplUtil.GetWeaponMap()[weaponId];
        }
    }

    protected float 존苾웵;
    public virtual float 존河 { get; }
    public float 존虐‰
    {
        get
        {
            if (GameManager.Instance.Player == null) return 1;
            return weaponInfo.AttckSpeed * GameManager.Instance.Player.attr.존虐‰ / 100.0f;
        }
    }

    public float 존何疸 { get { return 1.0f / 존虐‰; } }
    protected float 존何疸瑨lk;

    protected CircleCollider2D circleCollider;
    public List<Transform> enemyList;

    protected void Awake()
    {
        circleCollider = GetComponent<CircleCollider2D>();
    }

    protected virtual void Start()
    {
        enemyList = new List<Transform>();
    }

    public virtual void InitAttribute(int id)
    {
        this.weaponId = id;
        rankType = (RankType)weaponInfo.Rank;
        존苾웵 = weaponInfo.AttckRange;
        circleCollider.radius = 존苾웵;
    }

    protected virtual void Update()
    {
        if (존何疸瑨lk > 0) 존何疸瑨lk -= Time.deltaTime;
        else 존();
    }

    protected virtual void 존() {}

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.tag == "Enemy")
        {
            enemyList.Add(collision.transform);
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.tag == "Enemy")
        {
            enemyList.Remove(collision.transform);
        }
    }

    
}
